import { createServer } from "node:http";
import { exec } from "node:child_process";
import { randomUUID } from "node:crypto";
import { writeFile } from "node:fs/promises";
import path from "node:path";

const PORT = 8787;
const REDIRECT_URI = `http://localhost:${PORT}/callback`;
const SCOPES = ["w_member_social", "openid", "profile", "email"];
const ENV_OUT = path.join(process.cwd(), ".env.distribution");

function requireEnv(name) {
  const v = process.env[name];
  if (!v) {
    console.error(`\nMissing env: ${name}`);
    console.error(`Set it before running:`);
    console.error(`  export ${name}=...`);
    process.exit(2);
  }
  return v;
}

const clientId = requireEnv("LINKEDIN_CLIENT_ID");
const clientSecret = requireEnv("LINKEDIN_CLIENT_SECRET");

const state = randomUUID();
const authUrl = new URL("https://www.linkedin.com/oauth/v2/authorization");
authUrl.searchParams.set("response_type", "code");
authUrl.searchParams.set("client_id", clientId);
authUrl.searchParams.set("redirect_uri", REDIRECT_URI);
authUrl.searchParams.set("state", state);
authUrl.searchParams.set("scope", SCOPES.join(" "));

async function exchangeCode(code) {
  const res = await fetch("https://www.linkedin.com/oauth/v2/accessToken", {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: REDIRECT_URI,
      client_id: clientId,
      client_secret: clientSecret,
    }),
  });
  if (!res.ok) {
    throw new Error(`token exchange failed: ${res.status} ${await res.text()}`);
  }
  return res.json();
}

async function fetchMember(accessToken) {
  const res = await fetch("https://api.linkedin.com/v2/userinfo", {
    headers: { authorization: `Bearer ${accessToken}` },
  });
  if (!res.ok) {
    throw new Error(`userinfo failed: ${res.status} ${await res.text()}`);
  }
  return res.json();
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url, `http://localhost:${PORT}`);
  if (url.pathname !== "/callback") {
    res.writeHead(404).end("not found");
    return;
  }

  const code = url.searchParams.get("code");
  const returnedState = url.searchParams.get("state");
  const error = url.searchParams.get("error");

  if (error) {
    res.writeHead(400, { "content-type": "text/plain" }).end(`OAuth error: ${error}`);
    console.error(`\nLinkedIn returned error: ${error}`);
    process.exit(1);
  }

  if (!code || returnedState !== state) {
    res.writeHead(400).end("missing code or state mismatch");
    console.error(`\nState mismatch — possible CSRF. expected=${state} got=${returnedState}`);
    process.exit(1);
  }

  res.writeHead(200, { "content-type": "text/html" }).end(
    `<html><body style="font-family: system-ui; padding: 40px;">
      <h1>Handshake complete.</h1>
      <p>You can close this tab and check the terminal.</p>
    </body></html>`,
  );

  try {
    const tokens = await exchangeCode(code);
    const member = await fetchMember(tokens.access_token);
    const memberUrn = `urn:li:person:${member.sub}`;
    const issuedAt = new Date().toISOString();

    const envText =
      `# generated by scripts/linkedin-oauth.mjs at ${issuedAt}\n` +
      `LINKEDIN_CLIENT_ID=${clientId}\n` +
      `LINKEDIN_CLIENT_SECRET=${clientSecret}\n` +
      `LINKEDIN_ACCESS_TOKEN=${tokens.access_token}\n` +
      `LINKEDIN_REFRESH_TOKEN=${tokens.refresh_token ?? ""}\n` +
      `LINKEDIN_MEMBER_URN=${memberUrn}\n` +
      `LINKEDIN_REFRESH_TOKEN_ISSUED_AT=${issuedAt}\n`;

    await writeFile(ENV_OUT, envText, { mode: 0o600 });

    console.log("\n[linkedin-oauth] handshake OK.");
    console.log(`  member: ${member.name} <${member.email}>`);
    console.log(`  urn:    ${memberUrn}`);
    console.log(`  access token expires in ${tokens.expires_in}s (~${Math.round(tokens.expires_in / 86400)}d)`);
    if (tokens.refresh_token_expires_in) {
      console.log(`  refresh token expires in ${tokens.refresh_token_expires_in}s (~${Math.round(tokens.refresh_token_expires_in / 86400)}d)`);
    }
    console.log(`  wrote ${ENV_OUT} (chmod 600)`);
    console.log("\n[linkedin-oauth] paste these into GitHub Secrets:");
    for (const key of [
      "LINKEDIN_CLIENT_ID",
      "LINKEDIN_CLIENT_SECRET",
      "LINKEDIN_ACCESS_TOKEN",
      "LINKEDIN_REFRESH_TOKEN",
      "LINKEDIN_MEMBER_URN",
    ]) {
      console.log(`  gh secret set ${key} --body "$(grep '^${key}=' ${ENV_OUT} | cut -d= -f2-)"`);
    }
    server.close();
    process.exit(0);
  } catch (err) {
    console.error(`\n[linkedin-oauth] failed: ${err.message}`);
    process.exit(1);
  }
});

server.listen(PORT, () => {
  console.log(`[linkedin-oauth] listening on ${REDIRECT_URI}`);
  console.log(`[linkedin-oauth] opening: ${authUrl.toString()}`);
  exec(`open "${authUrl.toString()}"`, (err) => {
    if (err) {
      console.log("\nCouldn't open browser automatically. Paste this URL manually:");
      console.log(`  ${authUrl.toString()}`);
    }
  });
});
